env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROVIDER: artifactory
jobs:
  warn-sdk-prs:
    name: warn-sdk-prs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - id: check_schema_changed
      name: Check for diff in schema
      run: |-
        if git diff --quiet ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- provider/cmd/${PROVIDER}/schema.json; then
        echo "there is no diff in schema"
        else
        echo "The schema was changed; skip remaining steps"
        echo "::set-output name=schema_changed::changed"
        fi
    - id: check_sdk_changed
      if: steps.check_schema_changed.outputs.schema_changed == 'changed'
      name: Check for diff in sdk/*
      run: |-
        if git diff --quiet ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- sdk/*; then
        echo "there is no diff in SDK; skip remaining steps"
        else
        echo "The SDK had changes; send warning"
        echo "::set-output name=sdk_files_changed::sdk_changed"
        fi
    - if: steps.check_sdk_changed.outputs.sdk_files_changed == 'sdk_changed'
      name: Send codegen warning as comment on PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Hello and thank you for your pull request! :heart: :sparkles:
          It looks like you're trying to directly modify files in the language SDKs, many of which are autogenerated.
          Please double check that you have [correctly generated any code](https://github.com/pulumi/${{ github.event.repository.name }}/blob/master/CONTRIBUTING.md#committing-generated-code).
"on":
  pull_request_target:
    branches:
    - main
    - master
